version: "3"
services:
  postgres:
    container_name: pg-container
    image: postgres:latest
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      POSTGRES_DB: ruby-grape-clean-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"

  api:
    container_name: api-container
    image: ruby:latest
    working_dir: /usr/src/ruby-grape-clean-api
    restart: always
    command: bash -c "bundle install && rerun -- rackup -p 5050 -r ./src/main/server.rb -s puma -o 0.0.0.0 2>/dev/null"
    environment:
      POSTGRES_DB: ruby-grape-clean-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - ./src:/usr/src/ruby-grape-clean-api/src
      - ./Gemfile:/usr/src/ruby-grape-clean-api/Gemfile
      - ./config.ru:/usr/src/ruby-grape-clean-api/config.ru
      - ./Gemfile.lock:/usr/src/ruby-grape-clean-api/Gemfile.lock
      - ./package.json:/usr/src/ruby-grape-clean-api/package.json
    ports:
      - "5050:5050"
    links:
      - postgres
