version: "3"
services:
  postgres:
    container_name: pg-container
    image: postgres:latest
    env_file:
      - .env
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres_test:
    container_name: pg-test-container
    image: postgres:latest
    env_file:
      - .env.test
    restart: always
    volumes:
      - ./data_test:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    container_name: api-container
    image: ruby:latest
    working_dir: /usr/src/ruby-grape-clean-api
    restart: always
    command: bash -c "bundle install && ruby ./src/main/config/migrations.rb && rerun -- rackup -p 5050 -r ./src/main/server.rb -s puma -o 0.0.0.0 2>/dev/null"
    depends_on:
      - postgres
      - postgres_test
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - ./src:/usr/src/ruby-grape-clean-api/src
      - ./Gemfile:/usr/src/ruby-grape-clean-api/Gemfile
      - ./config.ru:/usr/src/ruby-grape-clean-api/config.ru
      - ./Gemfile.lock:/usr/src/ruby-grape-clean-api/Gemfile.lock
      - ./package.json:/usr/src/ruby-grape-clean-api/package.json
    ports:
      - "5050:5050"
