name: Run Tests

on: [push, pull_request]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ruby-grape-clean-api
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    strategy:
      matrix:
        node-version: [21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Use Ruby 3.3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Limpar cache do Bundler
        run: bundle clean --force

      - name: Install dependencies
        run: bundle install && npm install

      - name: Run Migrations
        run: |
          bundle exec ruby ./src/main/config/migrations.rb
        env:
          DRIVER: postgres
          POSTGRES_DB: ruby-grape-clean-api
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

      - name: Run Tests
        run: COVERAGE=true bundle exec rspec --format documentation --color
        env:
          DRIVER: postgres
          POSTGRES_DB: ruby-grape-clean-api
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

      - name: Run Coveralls
        uses: coverallsapp/github-action@v2
